LIBS = -lSDL3 -lGL
OWN_PATHS = -Isrc
HEADERS = $(OWN_PATHS) -I/usr/local/include
DEFINES =
CFLAGS = -std=c++20 -Wall -Wextra -O3 -ggdb
NAME = trigwars
OBJDIR = obj

SRC_DIRS = core entities render audio ui math vendor
SRC_FILES = $(foreach d,$(SRC_DIRS),$(wildcard src/$(d)/*.cpp))
OBJ_FILES = $(SRC_FILES:.cpp=.o)

OBJS = $(addprefix $(OBJDIR)/, $(OBJ_FILES))
DEPS = $(OBJS:.o=.d)

CLANG_ANALYZE   = #--analyze
CLANG_THREAD    = #-fsanitize=thread
CLANG_ADDRESS   = #-fsanitize=address
CLANG_MEMORY    = #-fsanitize=memory
CLANG_UNDEFINED = #-fsanitize=undefined

CLANG_FLAGS= $(CLANG_ANALYZE) $(CLANG_THREAD) $(CLANG_ADDRESS) $(CLANG_MEMORY) $(CLANG_UNDEFINED)

COMPILER = g++
#COMPILER = clang++

all: $(NAME)
	./$(NAME)

# dependencies
$(OBJDIR)/%.d : %.cpp | $(OBJDIR)
	@mkdir -p $(dir $@)
	$(COMPILER) -MM -MP -MT $(@:.d=.o) -o $@ $< $(CFLAGS) $(DEFINES) $(HEADERS)

# compiling
$(OBJDIR)/%.o : %.cpp | $(OBJDIR)
	@mkdir -p $(dir $@)
	$(COMPILER) -o $@ -c $< $(CFLAGS) $(CLANG_FLAGS) $(DEFINES) $(HEADERS)

clean:
	rm $(OBJDIR)/*

$(NAME): $(OBJS)
	$(COMPILER) -o $@ $(OBJS) $(LIBS) $(CLANG_FLAGS)

$(OBJDIR):
	mkdir -p $@

# Load .d files
ifneq ($(MAKECMDGOALS),clean)
-include $(DEPS)
endif
