LIBS = -lSDL3
OWN_PATHS = -Isrc
HEADERS = $(OWN_PATHS) -I/SDK/local/newlib/include
DEFINES =
CFLAGS = -std=c++20 -Wall -Wextra -O3 -gstabs
NAME = trigwars
OBJDIR = obj

SRC_DIRS = core entities render audio ui math vendor
SRC_FILES = $(foreach d,$(SRC_DIRS),$(wildcard src/$(d)/*.cpp))
OBJ_FILES = $(SRC_FILES:.cpp=.o)

OBJS = $(addprefix $(OBJDIR)/, $(OBJ_FILES))
DEPS = $(OBJS:.o=.d)

COMPILER = g++

all: $(NAME)
	#$(NAME)

# dependencies
$(OBJDIR)/%.d : %.cpp | $(OBJDIR)
	@mkdir -p $(dir $@)
	$(COMPILER) -MM -MP -MT $(@:.d=.o) -o $@ $< $(CFLAGS) $(DEFINES) $(HEADERS)

# compiling
$(OBJDIR)/%.o : %.cpp | $(OBJDIR)
	@mkdir -p $(dir $@)
	$(COMPILER) -o $@ -c $< $(CFLAGS) $(DEFINES) $(HEADERS)

clean:
	rm $(OBJDIR)/*

$(NAME): $(OBJS)
	$(COMPILER) -o $@ $(OBJS) $(LIBS) -athread=native

$(OBJDIR):
	mkdir -p $@

# Load .d files
ifneq ($(MAKECMDGOALS),clean)
-include $(DEPS)
endif
